name = "DST Mod"
description = "Not sure what I'm doing, we'll see.."
author = "wakemeupp"
version = "0.0.1"
forumthread = "/"
--icon_atlas = "modicon.xml"
--icon = "modicon.tex"
client_only_mod = true
dont_starve_compatible = true
reign_of_giants_compatible = true
dst_compatible = true
api_version = 10